In [ ]:
import torch

in pytorch everything is based on tensor operations.

a tensor can have different dimensions.

## **create an empty tensors**

In [ ]:
x = torch.empty(1) #size=1 like a scaler value that not initialized
print(x)

tensor([2.2473e-35])


In [ ]:
x = torch.empty(3)
print(x)

tensor([2.2474e-35, 0.0000e+00, 1.5975e-43])


In [ ]:
x = torch.empty(2,3)
print(x)

tensor([[2.2474e-35, 0.0000e+00, 1.4714e-43],
        [1.6255e-43, 1.4714e-43, 1.3593e-43]])


## **create a tensor with random values**

In [ ]:
x = torch.rand(2,2)
print(x)

tensor([[0.9614, 0.7878],
        [0.7754, 0.1362]])


## **create a tensor with all zero values**

In [ ]:
x = torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


## **create a tensor with all one values**

In [ ]:
x = torch.ones(2,2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


## **create a tensor with specific data type**

In [ ]:
x = torch.ones(2,2)
print(x.dtype) #print the default dtype

torch.float32


In [ ]:
x = torch.ones(2,2, dtype=torch.int)
print(x.dtype)

torch.int32


## **Size of a tensor**

In [ ]:
x = torch.ones(2,2, dtype=torch.int)
print(x.size())

torch.Size([2, 2])


## **Create a tensor**

In [ ]:
x = torch.tensor([0.1 , 2.5])
print(x)

tensor([0.1000, 2.5000])


## **Basic Operations**

In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)

print(x)
print(y)

tensor([[0.4773, 0.4380],
        [0.5438, 0.9163]])
tensor([[0.2174, 0.1041],
        [0.7954, 0.5111]])


> addition



In [ ]:
z = x + y
print(z)

tensor([[0.6947, 0.5421],
        [1.3392, 1.4274]])


In [ ]:
# it's do the same thing:
z = torch.add(x,y)
print(z)

tensor([[0.6947, 0.5421],
        [1.3392, 1.4274]])


In [ ]:
# in-place addition
y.add_(x)
print(y)

tensor([[0.6947, 0.5421],
        [1.3392, 1.4274]])


> subtraction



In [ ]:
z = x - y
z = torch.sub(x,y)
print(z)

tensor([[-0.2174, -0.1041],
        [-0.7954, -0.5111]])


> multiplication



In [ ]:
z = x * y
z = torch.mul(x,y)
print(z)

tensor([[0.3315, 0.2374],
        [0.7283, 1.3079]])


> division



In [ ]:
z = x / y
z = torch.div(x,y)
print(z)

tensor([[0.6870, 0.8079],
        [0.4061, 0.6419]])


## **Slicing**

In [ ]:
x = torch.rand(5,3)
print(x)

tensor([[0.8711, 0.4041, 0.0842],
        [0.5052, 0.4602, 0.7260],
        [0.6575, 0.3432, 0.5049],
        [0.0791, 0.6913, 0.3414],
        [0.0256, 0.4313, 0.8292]])


In [ ]:
print(x[:,0]) #all rows + only first columns

tensor([0.8711, 0.5052, 0.6575, 0.0791, 0.0256])


In [ ]:
print(x[1,:]) # rows number 1 + all columns

tensor([0.5052, 0.4602, 0.7260])


In [ ]:
print(x[1,1]) #get one element

tensor(0.4602)


In [ ]:
#if you have only one element in your tensor you can get that by:
print(x[1,1].item()) #this get you the actual value

0.46021944284439087


## **Reshape the tensor**

In [ ]:
x = torch.rand(4,4)
print(x)

tensor([[0.5362, 0.4643, 0.4067, 0.3270],
        [0.3451, 0.7747, 0.9230, 0.9235],
        [0.3520, 0.8123, 0.9601, 0.0060],
        [0.2461, 0.4652, 0.0471, 0.8805]])


In [ ]:
y = x.view(16)
print(y)

tensor([0.5362, 0.4643, 0.4067, 0.3270, 0.3451, 0.7747, 0.9230, 0.9235, 0.3520,
        0.8123, 0.9601, 0.0060, 0.2461, 0.4652, 0.0471, 0.8805])


In [ ]:
#if you want that pytorch determined the size, put the -1:
y = x.view(-1,8)
print(y)

tensor([[0.5362, 0.4643, 0.4067, 0.3270, 0.3451, 0.7747, 0.9230, 0.9235],
        [0.3520, 0.8123, 0.9601, 0.0060, 0.2461, 0.4652, 0.0471, 0.8805]])


In [ ]:
print(y.size())

torch.Size([2, 8])


## **Convert Numpy to the torch Tensor**

In [ ]:
import numpy as np

In [ ]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [ ]:
print(type(b))

<class 'numpy.ndarray'>


if you use cpu instead of gpu, a and b point to the same memory location.

so for confidence you can do this in your code:

In [ ]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5 , device=device)
  #or
  y = torch.ones(5)
  y = y.to(device)
  z = x + y #so this performs on gpu and must be faster
  # but z.numpy() get error because numpy can only handle cpu tensors 
  #so you cann't convert gpu tensor back to numpy
  #for handle this you can:
  z = z.to("cpu")

## **Convert torch Tensor to Numpy**

In [ ]:
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [ ]:
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


## **optimize the value**

In [ ]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
